version: '3'

services:

  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tqibank
    volumes:
      - ./mysql-volume:/var/lib/mysql
    ports:
      - 3307:3306